封装请求响应
xkcoding/simple-http pull request #11
Opened 2021-09-11 09:22 UTC by Mvbbb

1. 添加 simpleHttpResponse 类，包含 code（响应码），success（是否成功），header（响应头），body（响应体）字段，用于封装 http 响应
2. 不成功的 http 响应不再抛出 “Unexpected code”异常。而是封装为 simpleHttpResponse 类，使用者自行处理失败的请求响应

2021-09-13 03:25 UTC, xkcoding requested changes

2021-09-13 03:25 UTC, xkcoding commented on src/main/java/com/xkcoding/http/support/okhttp3/OkHttp3Impl.java
> +			Map<String, List<String>> headers = request.headers().toMultimap();
这里的 headers  是否取错了，应该取的是 response 的 headers 吧？

2021-09-13 04:00 UTC, Mvbbb commented on src/main/java/com/xkcoding/http/support/okhttp3/OkHttp3Impl.java
> +			Map<String, List<String>> headers = request.headers().toMultimap();
这儿的确有问题

2021-09-14 08:00 UTC, xkcoding approved these changes

2021-09-14 08:01 UTC, merged